# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
    - uses: actions/checkout@v3
    - name: 'Download Flutter'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
    - name: 'Get Dependencies'
    - run: flutter pub get
    - name: 'Setup Credentials'
    - run: |
        mkdir -p ~/.pub-cache
        cat <<EOF > ~/.pub-cache/credentials.json
        ${{ secrets.CREDENTIAL_JSON }}
        EOF
    - name: 'Publish Package'
    - run: flutter pub publish -f
