name: PR Build and Test

on:
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Download flutter'
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'
      run: flutter --version
     - name: 'Flutter pub get'
      run: 'flutter pub get'